def display_menu():
    print("\n----- TO-DO LIST MENU -----")
    print("1. Display Tasks")
    print("2. Add Task")
    print("3. Remove Task")
    print("4. Exit")

def display_tasks(tasks):
    if not tasks:
        print("\nNo tasks in your to-do list.")
    else:
        print("\nYour Tasks:")
        for i, task in enumerate(tasks, 1):
            print(f"{i}. {task}")

def add_task(tasks):
    task = input("\nEnter new task: ")
    tasks.append(task)
    print("Task added.")

def remove_task(tasks):
    display_tasks(tasks)
    if not tasks:
        return
    try:
        i = int(input("Enter task number to remove: "))
        if 1 <= i <= len(tasks):
            remove= tasks.pop(i - 1)
            print(f"Removed task: {remove}")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

def main():
    tasks = []
    while True:
        display_menu()
        choice = input("Select an option (1-4): ")
        if choice == '1':
            display_tasks(tasks)
        elif choice == '2':
            add_task(tasks)
        elif choice == '3':
            remove_task(tasks)
        elif choice == '4':
            print("Goodbye!")
            break
        else:
            print("Invalid option. Please choose between 1 and 4.")
if __name__ == "__main__":
    main()
    main
